#!/bin/bash

# Get the current block number from a Cloud Ethereum node using basic
# authentication.

curl \
  -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":"0"}' \
  -H "Content-Type: application/json" \
  -k \
  -u "$USER:$PASS" \
  -w "\n" \
  -X POST \
  "https://$IP:8545"
